### ISSUE TITLE
Client & Server separation

### ISSUE THREAD

**Issue by apokalyptik** [nylen/lockd#2]
It *looks* like you might be making preparations for the same package (or object) to be both client and server.  If so Consider not combining the two in the same objects (at least)... having a bunch of "if server {}  else {}" sprinkled is unnecessary and hurts readability

**Comment by nylen** [comment]
I agree.  I plan to release one package, but keep the objects separate in the `client/` and `server/` directories and factor common functions out into `lib/`.

I debated this choice a little, and chose to keep them together because:

- Easier administration (only need to update and release 1 package)
- Ensures that client and server versions are compatible
- It's natural to test client and server together

The main benefit of having 2 separate packages would be for each package to "do one thing and do it well", but the client and the server are closely related, and if you only need the client or the server, packaging a few extra KB of code isn't a big deal.

Open to discussion on that, and definitely let me know if you see the `if (server)` pattern creeping in anywhere.

**Comment by apokalyptik** [comment]
I'm not swinging the ban-hammer here, just holding my end of the debate...

"few extra KB of code isn't a big deal" I'm not sure I agree with that in the long run. What you find (and we've found with large PHP projects) is that after several years of adding code you suddenly have so much code that things like compilation, vcs, and tooling speed begin to become a factor. That said one single component can't fix an ecosystem wide problem. Additionally shared code could easily be a third component that either or both depend on.

Your three bulleted points are good ones, however, especially the one about testing.

**Comment by apokalyptik** [comment]
Since my comment was mostly about readability, though, as long as you can keep the logic clean and avoid constantly nesting via control structures to arrive at your goal I'll be happy

**Comment by nylen** [comment]
sounds good.
